export const LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'ja', name: '日本語' },
  { code: 'es', name: 'Español' },
  { code: 'fr', name: 'Français' },
  { code: 'de', name: 'Deutsch' },
  { code: 'zh', name: '中文' },
] as const;

export const TRANSLATIONS = {
  en: {
    settings: 'Settings',
    interfaceLanguage: 'Interface Language',
    studyLanguage: 'Study Language',
    addWord: 'Add New Word',
    search: 'Search your vocabulary...',
    enterWord: 'Enter a word',
    generateMeaning: 'Generate AI Explanation',
    save: 'Save to Notebook',
    noWords: 'No words added yet',
    noMatches: 'No matching words found',
    added: 'Added',
    details: 'Details',
    examples: 'Examples',
    mastery: 'Mastery',
    lastReviewed: 'Last Reviewed',
    addExample: 'Add Example',
    startQuiz: 'Start Quiz',
    quiz: 'Flashcards',
    flipCard: 'Flip Card',
    correct: 'I knew it',
    incorrect: "Didn't know",
    next: 'Next Card',
    finish: 'Finish',
    score: 'Score',
    tryAgain: 'Try Again',
    progress: 'Progress',
    tags: 'Tags',
    addTag: 'Add Tag',
    review: 'Review',
    startLearning: 'Start Learning',
    tapToFlip: 'Tap to flip',
    cardsRemaining: 'Cards remaining',
  },
  ja: {
    settings: '設定',
    interfaceLanguage: '表示言語',
    studyLanguage: '学習言語',
    addWord: '新しい単語を追加',
    search: '単語を検索...',
    enterWord: '単語を入力',
    generateMeaning: 'AI説明を生成',
    save: 'ノートブックに保存',
    noWords: '単語がまだありません',
    noMatches: '一致する単語が見つかりません',
    added: '追加日',
    details: '詳細',
    examples: '例文',
    mastery: '習熟度',
    lastReviewed: '最終復習日',
    addExample: '例文を追加',
    startQuiz: '学習を開始',
    quiz: 'フラッシュカード',
    flipCard: 'カードを裏返す',
    correct: '覚えていた',
    incorrect: '覚えていなかった',
    next: '次のカード',
    finish: '終了',
    score: 'スコア',
    tryAgain: 'もう一度',
    progress: '進捗',
    tags: 'タグ',
    addTag: 'タグを追加',
    review: '復習',
    startLearning: '学習を開始',
    tapToFlip: 'タップして裏返す',
    cardsRemaining: '残りのカード',
  },
} as const;